import './globals.css'
import ico from '../app/favicon.ico'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Furniture-Store',
  description: 'Generated by create next app',
  icons: ico
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  )
}
